### ISSUE TITLE
Display text before poll options

### ISSUE THREAD

**Issue by rupalkhilari** [electology/approval_frame#102]
Immediately before the options, display text "Choose as many options as you wish." This will reinforce the concept of approval voting.

**Comment by kushankr** [comment]
I will take this one too. It is a very small change. Will be ready by tonight.

**Comment by kushankr** [comment]
Initiated a PR

#105 

Can you please review it, Rupal? Thanks a lot.

**Comment by rupalkhilari** [comment]
Looks good. Thanks Kushank !
