### ISSUE TITLE
Make poll leader bar highlighted as the default

### ISSUE THREAD

**Issue by rupalkhilari** [electology/approval_frame#104]
Currently this option is configurable in the poll settings panel ("Show Leading option in different color.") . Have this enabled by default.

**Comment by kushankr** [comment]
Hi @rupalkhilari ,

I just made a comment regarding this in #78 

I will go ahead and take this issue. I will have this option enabled by default.

**Comment by rupalkhilari** [comment]
Oh alright, thanks @kushankr !

**Comment by kushankr** [comment]
Initiated a PR

#105 

Can you please review it, Rupal? Thanks a lot.

**Comment by rupalkhilari** [comment]
Looks good, merged it in. Thanks !
