### ISSUE TITLE
Ability to edit poll question and poll choices.

### ISSUE THREAD

**Issue by rupalkhilari** [electology/approval_frame#108]
Allow editing poll question and poll choices. The poll admin should not be allowed to edit the poll question or choice if it has already got a ballot on it.

**Comment by nraghun** [comment]
Hi, 
Is this being worked on by anybody? 

I see the options for the polls as 'edit', 'suspend' and 'remove'. Not sure if this is the correct place for this question - a question about 'remove' option - Can a poll be removed after it has a ballot in it? 

Thanks
Neeti

**Comment by octy40** [comment]
Hi @nraghun, I was looking into this issue, but feel free to take it. I'm still learning Django and haven't been able to figure out this part yet.

As for the suspend, I'm not sure, but I imagine a poll admin should be able to suspend a poll whenever they want, with or without ballots.

**Comment by rupalkhilari** [comment]
Hi @nraghun , yes, currently the poll admin can remove a poll even if it has a ballot in it. It will delete the poll and the corresponding ballots. You should be able to see the delete poll functionality in 'Manage your polls' . It was handled in https://github.com/electology/approval_frame/issues/65

**Comment by balajisubr** [comment]
Is someone currently working on this?

**Comment by rupalkhilari** [comment]
@balajisubr looks like the last update was a year back, so I think you should go ahead with it if you have the time to take it up.

**Comment by balajisubr** [comment]
@Faxn seems like you have made some changes for editing poll question and choices as recent as May '17. Just want to make sure you are not working on this issue currently.

**Comment by rupalkhilari** [comment]
Closing this. Thanks @balajisubr
