### ISSUE TITLE
Allow editing poll voting type

### ISSUE THREAD

**Issue by rupalkhilari** [electology/approval_frame#109]
Allow editing poll type (Anyone allowed to vote, logged in users allowed to vote, email Id owners allowed  to vote). If additional emails are added, it should send a new voting invitation to those members. It could also give the ability to resend a vote invitation to someone.

**Comment by hmurali** [comment]
I am currently taking up this ticket.

**Comment by balajisubr** [comment]
@rupalkhilari I am taking up this and #111 next

**Comment by balajisubr** [comment]
@rupalkhilari During what point of time should the editing of this be stopped for a poll?

**Comment by rupalkhilari** [comment]
@balajisubr , I think we should allow the poll to be edited anytime, even after it expires (in case the poll admin wanted to reopen the poll). Do you have any use cases for not allowing a poll to be edited ?

**Comment by rupalkhilari** [comment]
Addressed in https://github.com/electology/approval_frame/pull/139 . Closing this. 
Thanks @balajisubr !
