### ISSUE TITLE
Allow editing poll close date and times and display/countdown.

### ISSUE THREAD

**Issue by rupalkhilari** [electology/approval_frame#110]

**Comment by erswatiaggarwal** [comment]
Hi Rupal,I am planning to take this issue.

**Comment by erswatiaggarwal** [comment]
Hi Rupal,

As per my analysis these are file need to be touch
approval_frame/approval_polls/migrations/0006_poll_show_close_date.py
approval_frame/approval_polls/migrations/0007_poll_show_countdown.py
approval_frame/approval_polls/models.py

Here we need to make sure default functionality for show_countdown and time_close should be true.
I can't test changes as main functionality edit on poll is not working yet.So whats your suggestions for this.

**Comment by rupalkhilari** [comment]
Sorry @erswatiaggarwal I was a bit caught up at work. The migration files are auto-generated when you run python manage.py makemigrations . I'm not clear why we need to change the default behavior. Could you elaborate ? 
I think the edit screen should read the current settings for the poll and display them in the page, and allow the user to update them.

**Comment by erswatiaggarwal** [comment]
HI @rupalkhilari 

if i am understanding problem correctly, we are trying to edit poll which is already created.
Now in site  when you click on manage poll setting,three button edit,suspend etc displayed.In case edit click nothing happens,which we want it to work.Here As the problem statement,I am just trying to work on edit of attribute of created poll which is poll_show_closed_date/poll_show_countdown.This attribute will enable only when edit button works.This is another issue
Add ability for users to manage polls: edit poll #66

As per my understanding i can't test this one,till the time reference issue is not solved.Please let me know.

**Comment by rupalkhilari** [comment]
Hi @erswatiaggarwal , since the edit had no functionality yet there is no page associated with it. I would encourage you to add the page from which the poll admin will be allowed to edit the poll_show_closed_date and poll_show_countdown.

**Comment by Faxn** [comment]
Can this be closed now, or is there some aspect to this issue that #127 didn't address?

**Comment by rupalkhilari** [comment]
Yes @Faxn , this can be closed now, thanks!
