### ISSUE TITLE
Maintain a list of users subscribed to the newsletter through the app

### ISSUE THREAD

**Issue by rupalkhilari** [electology/approval_frame#115]
It would be nice to know the number of users who are subscribing to the newsletter via the poll app.

**Comment by rupalkhilari** [comment]
https://github.com/electology/approval_frame/issues/116 has already included a model to store the list of users subscribed to the newsletter through the app. Connect this logic to the registration page as well.

**Comment by balajisubr** [comment]
@rupalkhilari Looks like https://github.com/electology/approval_frame/pull/122 has already addressed this.

**Comment by balajisubr** [comment]
@rupalkhilari  Can this be considered closed?

**Comment by rupalkhilari** [comment]
@balajisubr , yes, thanks!!
