### ISSUE TITLE
Provide an interface to subscribe to the newsletter in the account page

### ISSUE THREAD

**Issue by rupalkhilari** [electology/approval_frame#116]
Similar to the option on the 'register' screen, provide an interface to the user to subscribe to the newsletter in the login screen. Make sure duplicate emails are handled appropriately.

**Comment by balajisubr** [comment]
@rupalkhilari Is this for logged in users? If so, it would be better to add this in approval_polls/my-info/

**Comment by rupalkhilari** [comment]
@balajisubr - yes indeed, I had reviewed this with Aaron again and we thought that it would be better if this option is put into the user's account page instead of the login screen. Hope this is clearer, thanks for checking

**Comment by balajisubr** [comment]
@rupalkhilari Can this be considered closed?

**Comment by rupalkhilari** [comment]
@balajisubr , yes alls good!
