### ISSUE TITLE
New base template/styling used inconsistently

### ISSUE THREAD

**Issue by mudlock** [electology/approval_frame#12]
We started using a new base template (currently called public_base); major identifiable difference is the CES logo being at the bottom of the screen instead of the top.

But it's being used inconsistently.

-Is there a reason we need two templates? Or can we combine them into one? (If one, let's go with the name 'base'.)

-Is there any reason we can't move the attending css in public_base in with the rest of the css?

**Comment by ashimaathri** [comment]
Should look at this when working on #5

**Comment by ashimaathri** [comment]
Fixed by #59
