### ISSUE TITLE
Allow poll to be shared on social media

### ISSUE THREAD

**Issue by rupalkhilari** [electology/approval_frame#121]
Aaron had suggested adding social media sharing buttons to the poll (Facebook, twitter, email, linkedin, Google+) . Evaluate an appropriate jQuery plugin to be used for this task.

**Comment by CCInCharge** [comment]
I'll look into this if no one's started this yet - I'm new to django, but have some ideas on implementing this

**Comment by rupalkhilari** [comment]
Great! Thanks, Chen.
