### ISSUE TITLE
Script to keep subscribers of newsletter from app in sync

### ISSUE THREAD

**Issue by rupalkhilari** [electology/approval_frame#124]
Users subscribed to the newsletter through the Django app may choose to unsubscribe to the newsletter from outside the app. In this case, we want to be able to keep our record of subscribers from the app in sync to some extent with the real data. 
For this we could add a python script under approval_frame/scripts that reads the list of users from the local table and verifies their subscription status through the mailchimp API. If not subscribed, it should remove the local entry from subscribers. 
We plan to run this script as a cron on the production server to keep this data in sync to some extent

**Comment by rupalkhilari** [comment]
https://github.com/electology/approval_frame/pull/122 performs deletion and addition.

**Comment by balajisubr** [comment]
@rupalkhilari I am taking this up next.

**Comment by rupalkhilari** [comment]
Thanks @balajisubr !
