### ISSUE TITLE
Display username that created a poll

### ISSUE THREAD

**Issue by mudlock** [electology/approval_frame#13]

**Comment by Brianjr0428** [comment]
HI,
I am trying to understand more detail about this issue.
It seems like we need to make the username of the each poll's creator displayed in the detail page when voting. 
If my understanding is correct,  my thought will be:

1) add one field "username" to the approval_polls_poll table
2) pass the username of creator along with other fields when creating new poll 
3) display the username of creator in the detail page(wherever you would like to add)

Please let me know if I am on the right track.
Thanks!

Tzu-Feng

**Comment by ashimaathri** [comment]
@Brianjr0428 Thanks for looking into this issue! The steps that you've outlined are correct. Some additions to these steps are

1. Instead of a username field, we could have a user field that is a foreign key pointing to the User table of Django.contrib.auth. This way, we can ensure that all polls are associated with some existing user and the DB will do this validation for us.
3. We could also add the username next to the poll question in the index page along with the details page.

**Comment by Brianjr0428** [comment]
@ashimaathri 
Thanks for your reply. Just one more thing.
I am not sure if the username is unique, so is it a good idea to associate not only username but email address of the creator with each poll?

**Comment by ashimaathri** [comment]
@Brianjr0428 Sorry, I meant the User _model_ of Django.contrib.auth not table. The table that corresponds to this  model in the database is `auth_user`. The image you've taken only shows the indices on the tables, not the table names. If you scroll up, you should be able to see the table `auth_user`.
The registration module already ensures that the usernames are unique. PR #50 makes the email also unique. So associating the poll with a User instance through the foreign key relationship will ensure that the poll is associated with one user with a unique username and unique email ID.

**Comment by Brianjr0428** [comment]
@ashimaathri Yes I know it's just index, just wanted to show there are all names I can see since it's difficult to show all table names in one snapshot.
Thanks for your clarifying, I will try to work on this issue!

**Comment by ashimaathri** [comment]
@Brianjr0428 Great, thanks!

**Comment by Brianjr0428** [comment]
Hi @ashimaathri ,
If the user record (int case) is removed, should the polls created by that user be deleted as well?
I am thinking about how to update the poll table now.
Thanks!

**Comment by ashimaathri** [comment]
@Brianjr0428 That is correct. We can safely assume that if a user wants to delete his/her account, they will not want to see the results of their poll. To create, manage and view the results of a poll, one must be logged in to the system.
Looks like Django does a cascade delete [by default](https://docs.djangoproject.com/en/1.8/ref/models/fields/#django.db.models.ForeignKey.on_delete) for foreign key references, so we won't have to write any extra code for it.

**Comment by Brianjr0428** [comment]
@ashimaathri I've sent pull request, you can take a look when you get a chance.
Besides the requirements, I've also adjusted the width for the index page so that creator of each poll can display as well as poll questions.
Let me know if it's not appropriate.
Thanks!

**Comment by ashimaathri** [comment]
@Brianjr0428 Thanks! I will take a look at it as soon as possible.

**Comment by Brianjr0428** [comment]
@ashimaathri No problem. Would you like me to send you my .sqlite3 file for review?

**Comment by ashimaathri** [comment]
@Brianjr0428 Thanks for asking! That will not be necessary though, your code will work with any database. As you're going to change the schema, you will have to create a [migration](https://docs.djangoproject.com/en/1.8/topics/migrations/) and check it in as part of the PR though.

**Comment by Brianjr0428** [comment]
@ashimaathri 
Thanks for your feedback.
It looks like I need to get more familiar with Django as well as Python.
I will look into them more deeply and fix the issues ASAP.
Thank you!

**Comment by ashimaathri** [comment]
@Brianjr0428 It was a good first try though. I faced similar issues when I started web development. It's hard to keep security, performance and correctness in the mind while programming for the web but you will soon get used to it :smile: 
Feel free to ask questions if you feel stuck.

**Comment by Brianjr0428** [comment]
Thank you!
Just give me some time and I think I will make some progress!
