### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by ashimaathri** [electology/approval_frame#28]
Tests fail with status - `FAILED (errors=10, skipped=1, expected failures=1)`
The error in most cases appears to be `NoReverseMatch: u'approval_polls' is not a registered namespace`

**Comment by rupalkhilari** [comment]
Hi Ashima, 

Were these tests fixed ? I am currently running into the following issue https://github.com/electology/approval_frame/issues/37 with the tests:

Thanks, 
Rupal

**Comment by ashimaathri** [comment]
@rupalkhilari I still see these errors when i run `./manage.py test`.

**Comment by ashimaathri** [comment]
This looks related to a Django bug - https://code.djangoproject.com/ticket/11077. The long term solution is to upgrade Django to v1.8 from v1.5. The short term solution is to just run app specific tests using `./manage.py test approval_polls`

**Comment by rupalkhilari** [comment]
Oh ok, yes Ashima, I believe I wasn't able to see these errors when I ran it against django 1.6.11, even with ```./manage.py test``` . Have upgraded to v1.8.1 now.
