### ISSUE TITLE
Integrate with a continuous integration system like Travis CI

### ISSUE THREAD

**Issue by ashimaathri** [electology/approval_frame#40]

**Comment by Daniel-Avila** [comment]
I regularly set up CI with Jenkins. This is something well with in my ablity if you would like to chat about it.

**Comment by ashimaathri** [comment]
@Daniel-Avila that sounds great! Would it be possible for you to integrate it with Travis instead (because we don't have any dedicated infrastructure for this project and Travis is free for open source projects)?

**Comment by Daniel-Avila** [comment]
Sure .. ive never used travis before but Im sure I can do it. 
Do you have any details?

**Comment by Daniel-Avila** [comment]
@ashimaathri Ok we are going to have to work a little more closely with this. 

I don't have access to the electology repo so I cannot create the account or give authorization for TravisCI once that is done by someone with read/write permissions on the approval_frame repo and creates a TravisCI admin account for me I can get it set up.

**Comment by cwsusa** [comment]
@Daniel-Avila Are you auto-installing-configuring? I've experience with Chef (and a little ansible, which I don't like) can help if you've more left to do than wait on the access and admin account.

**Comment by rupalkhilari** [comment]
Addressed in #137 , thanks!
