### ISSUE TITLE
Highlight winner when poll is over

### ISSUE THREAD

**Issue by ashimaathri** [electology/approval_frame#46]

**Comment by Brianjr0428** [comment]
@ashimaathri I am thinking about doing this.
When #66 is fixed. Could you let me know what kind of highlight you would like for the winner of closed poll?
Thanks.

**Comment by ashimaathri** [comment]
Thanks @Brianjr0428. To start with, the [`text-success`](http://getbootstrap.com/css/#helper-classes-colors) class along with a [label](http://getbootstrap.com/components/#available-variations) that says winner would be good. We can discuss if it needs to be modified after looking at the final result.

**Comment by Brianjr0428** [comment]
Thanks @ashimaathri.
Since the winner will be highlighted after the poll is over, I can wait until the model has been modified with close date.
Let me know if you have different thought.
Thank you.

**Comment by octy40** [comment]
Hey @rupalkhilari  I wanted to take a stab at this issue, but due to my newness to Django. I'm a bit lost to where to look or start. Can you give me, if you can, simple directions?

**Comment by rupalkhilari** [comment]
Hi @octy40 , you should start with understanding the layout of the Django project structure, approval_frame project layout and [how Django implements MVC](https://docs.djangoproject.com/en/1.8/faq/general/#django-appears-to-be-a-mvc-framework-but-you-call-the-controller-the-view-and-the-view-the-template-how-come-you-don-t-use-the-standard-names).

I encourage you to take your time looking around the project and figure out the flow of data. 
Once you are familiar with it, for this issue, you should start with looking into these 2 files: 
* `ResultsView` class in [approval_polls/views.py](https://github.com/electology/approval_frame/blob/master/approval_polls/views.py#L81) - You could add a [get_context_data(self, kwargs**)](https://docs.djangoproject.com/en/1.8/ref/class-based-views/mixins-single-object/#django.views.generic.detail.SingleObjectMixin.get_context_data) to find the `winners` list of choices if the poll close date has passed. You should check [this implementation](https://github.com/electology/approval_frame/blob/master/approval_polls/views.py#L67) of get_context_data() in DetailView. 
* [approval_polls/templates/approval_polls/results.html](https://github.com/electology/approval_frame/blob/master/approval_polls/templates/approval_polls/results.html) . At the iteration over choices, check if the choice is one of the `winners`, if so, display a winner label  (you could also use a bootstrap [glyphicon](http://getbootstrap.com/components/#glyphicons) in addition to the label) 

This is one of the ways I would approach it. Please feel free to use another method if you see benefits. 
All the best ! Feel free to ask questions if needed.

**Comment by octy40** [comment]
Thanks @rupalkhilari . Appreciate all the insights; I'll play around and see what I can come up with.

**Comment by rupalkhilari** [comment]
The first bit of this ticket is being implemented as a part of #78 , so you may need to take care of presenting the winners as a part of this ticket. Thanks!

**Comment by kushankr** [comment]
Hi @rupalkhilari ,

Can I please take this issue? This issue was last updated 2 months back. Most of what this ticket needed has already been implemented in #78. Hence, I would like to work on this.

**Comment by rupalkhilari** [comment]
@kushankr since you implemented the other bit part of it, you could go ahead and completing this part to highlight the winner as well. @octy40 let us know in case you have any concerns.

**Comment by kushankr** [comment]
Thank you, Rupal.

**Comment by kushankr** [comment]
This is done.

Covered in PR #105 .

**Comment by kushankr** [comment]
@rupalkhilari 

Hi Rupal, you mentioned a comment in PR 105: "http://electologyapp.privatedns.org:8001/approval_polls/20/results/ this seems to show all are winners since they have 0 votes. Would it be better to add a message saying that 'No votes in this poll' and avoid tagging them are winners. This is subjective though."

i agree, I thought that my code took care of this scenario. I will work to fix this. Thank you for pointing this out. Thanks a lot.

**Comment by kushankr** [comment]
@rupalkhilari 

I have initiated a PR for the above change: #106 

Can you please review it, Rupal? Thank you.

**Comment by rupalkhilari** [comment]
Thanks for taking care of that, Kushank. Have merged the PR. Closing this.
