### ISSUE TITLE
Limit poll to specific e-mails set by poll administrator

### ISSUE THREAD

**Issue by ashimaathri** [electology/approval_frame#47]
The administrator of a poll limits the respondents to only those with specific e-mails. Accounts not attached to the listed e-mails cannot participate in the poll. This feature should be able to be turned on or off by the poll administrator.

**Comment by rupalkhilari** [comment]
Evaluating (django-invitation)[https://pypi.python.org/pypi/django-invitations/1.6] and other options for this.

**Comment by rupalkhilari** [comment]
django-invitation is quite user registration oriented, which not be necessary at present. The private/public polls coupled with vote invitation based model seems to be working well enough at present. Working on getting this and associated tests in place. 
One point to note is that for now the owner of the poll will also be allowed to vote in a poll that he/she has created.

**Comment by rupalkhilari** [comment]
#97 
Minor formatting change in https://github.com/electology/approval_frame/pull/100.
Closing this.
