### ISSUE TITLE
Allow password reset for forgotten username/password associated with e-mail.

### ISSUE THREAD

**Issue by ashimaathri** [electology/approval_frame#48]

**Comment by rupalkhilari** [comment]
Hi, I will be looking into this issue. Perhaps in the future we should also allow the user to change his/her password and email ID associated with the account.

**Comment by ashimaathri** [comment]
That would be a good idea. We could have a 'My Account' page with all the relevant details about the user.

**Comment by rupalkhilari** [comment]
Implemented in PR - https://github.com/electology/approval_frame/pull/64
