### ISSUE TITLE
Permit write-in option

### ISSUE THREAD

**Issue by ashimaathri** [electology/approval_frame#49]
Participants, when viewing the selection options within a poll, can add an additional option by typing it in and select that option if they choose. This feature should be able to be turned on or off by the poll administrator.

**Comment by kushankr** [comment]
I am working on this!

**Comment by kushankr** [comment]
Initiated a PR

#96

**Comment by rupalkhilari** [comment]
Addressed in https://github.com/electology/approval_frame/pull/96 . Thanks, Kushank !
