### ISSUE TITLE
Better CSS Classing for Styling

### ISSUE THREAD

**Issue by mudlock** [electology/approval_frame#5]
Make better use of ids and classes everywhere so people can more-easily style their deployment.

**Comment by ashimaathri** [comment]
We could use an existing CSS framework like [Bootstrap](http://getbootstrap.com/) to style the pages. This gives us the added benefits of responsiveness. As the framework is quite popular, many people will be familiar with it and will be able to customize the application styles according to their needs. Bootstrap is quite simple to use and pretty useful.

**Comment by octy40** [comment]
Hi Ashima - I'm new at this and was wondering if it was possible for you to give a little bit of guidance on how best to go about doing this enhancement?

**Comment by ashimaathri** [comment]
@octy40 It's great to know that you want to work on this issue!
I would suggest going through the [Bootstrap](http://getbootstrap.com/) website and getting acquainted with it by writing some sample html + css using bootstrap classes.
Then, you could incorporate the bootstrap grid-based layout and other relevant css styles (to forms for example) to our html.
I hope that will help get you started. Let me know of any questions you encounter on the way!

**Comment by ashimaathri** [comment]
Fixed by #59
