### ISSUE TITLE
Adding a local_settings.py file

### ISSUE THREAD

**Issue by rupalkhilari** [electology/approval_frame#56]
Would it be a good idea to import our local settings from a local_settings.py file into the main settings.py ? I find it very useful while developing (specifically the EMAIL_* related settings for registration which shouldn't be committed into settings.py)

We could do either 1 or 2 depending on what is agreeable.
1) Overwriting variables - import variables from local_settings.py into settings.py at the end which would overwrite the values. (http://stackoverflow.com/questions/4909958/django-local-settings). I prefer this since it is straightforward.
2) Extending variables - import settings into local_settings.py so that the variables in the settings file could be extended (https://gist.github.com/burnash/e60351e2696f4d17a466)

Also, adding local_settings.py to .gitignore. This way we could also switch DEBUG=True in the local_settings.py file. 

Please let me know your views. 

Thanks!

**Comment by ashimaathri** [comment]
@rupalkhilari that will be extremely helpful! I am with you on the first option (overwriting vars + a debug flag).

**Comment by ashimaathri** [comment]
Fixed by #57
