### ISSUE TITLE
Fix serving of static files when DEBUG=False

### ISSUE THREAD

**Issue by ashimaathri** [electology/approval_frame#62]
Django doesn't serve static files in production, so we have to configure another web server like apache and include instructions in the README.md.

See https://docs.djangoproject.com/en/1.8/howto/static-files/deployment/

**Comment by Daniel-Avila** [comment]
This is something well within my ability if I had access to do it.

**Comment by ashimaathri** [comment]
Hi @Daniel-Avila. Thanks for taking a look at this. Could you include the instructions in the README and submit a PR for it?

**Comment by rupalkhilari** [comment]
Addressed in https://github.com/electology/approval_frame/pull/86

**Comment by rupalkhilari** [comment]
This has been deployed on the server. Made use of [dj-static](https://pypi.python.org/pypi/dj-static) to help the app serve static files in production, when DEBUG=FALSE. 
Updated the README.md to include deployment instructions. Also added a 404.html page that will be displayed in case the target page is not found (such as [this](http://104.236.228.34:8001/approval_polls/some_invalid_url))
