### ISSUE TITLE
Add ability for users to manage polls: delete poll

### ISSUE THREAD

**Issue by Brianjr0428** [electology/approval_frame#65]

**Comment by Brianjr0428** [comment]
@ashimaathri 
My idea for this issue is when the user click the remove button, a pop-up windows shows to confirm removal. Once it has been confirmed, the page will be redirected to a confirm page.
Let me know if this is what you want.
Thanks.

**Comment by ashimaathri** [comment]
I like the popup idea (you can use [bootstrap's alert](http://getbootstrap.com/components/#alerts) component for this). I didn't understand why the user should be redirected to a confirm page though. We can just stay on the  same page right?

**Comment by Brianjr0428** [comment]
That's correct. 
Actually I've tried for a while yesterday and so far my understanding is the poll id has to be passed as the request and it will have to show in the URL. In that case, the page can't remain the same (../approval_polls/my-polls/) since the url for my_poll does require any id (../approval_polls/<id>/my-polls/) .
I can elaborate if you don't understand what I mean.

**Comment by ashimaathri** [comment]
You are right about the poll id being required in the url. As per the [REST interface] (https://en.wikipedia.org/wiki/Representational_state_transfer#Uniform_interface) specifications, the url for deletion should be the same as the url to access the poll. The only difference will be that to access the poll, we use an HTTP GET request but to delete it we will use an HTTP DELETE request.

For a good user experience, we will need to make this request through JavaScript using the jQuery [ajax method](http://api.jquery.com/jQuery.ajax/), so there will be no refreshes or page redirects.

**Comment by ashimaathri** [comment]
In JavaScript, we will have to register an event handler for the 'click' event on the delete button. This should show a boostrap alert with the confirmation and cancellation buttons. 

The cancellation button should do nothing other than close the alert box  (in its click event handler).

The confirmation button's 'click' event handler should make the ajax request to the server. Then the server will delete the record from the database and respond with a 200 OK message. After this we can remove the div (`<div class=well well-sm'`) containing the poll information using the [jQuery remove](https://api.jquery.com/remove/) method.

**Comment by Brianjr0428** [comment]
Thanks!
I will dig into that.
This is a very good front-end learning experience!

**Comment by Daniel-Avila** [comment]
So is this one moving forward? I can take it if nobody is working on it.

**Comment by Brianjr0428** [comment]
I'm working on it and waiting for the feedback from ashimaathri.
I think you can work on other issues unless ashimaathri wants you to take it.
Thanks.

**Comment by ashimaathri** [comment]
@Brianjr0428, @Daniel-Avila, sorry for the confusion. We should look more into the issue tracker idea that @Daniel-Avila has suggested to avoid stepping on each other's toes!

**Comment by rupalkhilari** [comment]
For volunteers - Since the previous developer of this feature is busy at present, this issue is available for anyone who is interested in tackling it.

**Comment by kushankr** [comment]
I think I am going to work on this!

**Comment by kushankr** [comment]
Initiated a PR

#96

**Comment by rupalkhilari** [comment]
Addressed in https://github.com/electology/approval_frame/pull/96 . Thanks, Kushank !
