### ISSUE TITLE
Integrating social authentication

### ISSUE THREAD

**Issue by rupalkhilari** [electology/approval_frame#69]
It'd be nice to integrate social authentication that would allow users with Google/Facebook/Twitter accounts to login, (and probably vote) without requiring them to create an account on the polls application. [This](https://python-social-auth.readthedocs.org/en/latest/) may be a good resource.

**Comment by kushankr** [comment]
Have started working on this!

**Comment by kushankr** [comment]
Initiated a PR

#95

**Comment by rupalkhilari** [comment]
The integration work really well. Thanks Kushank, for promptly addressing the issues ! #95 
Closing this.
