### ISSUE TITLE
Add an account information page for a user

### ISSUE THREAD

**Issue by rupalkhilari** [electology/approval_frame#72]
The username at the bottom of the panel could link to the user's account information - which includes some useful statistics about the user:
1) Member since (date)
2) Last login (date)
3) Total number of polls created (and a link to them). 
4) Change username and/or email. 
4) Change password. (Adding this requirement to another ticket) 
5) Opt in/out for newsletter subscription. (After https://github.com/electology/approval_frame/issues/33 is implemented)

... and any other information that might be useful.

**Comment by kushankr** [comment]
I am working on this.

**Comment by kushankr** [comment]
Done with this! Incorporated the feedback Rupal gave.

Testing now!

**Comment by rupalkhilari** [comment]
Cool..Thanks for looking into it !

**Comment by kushankr** [comment]
@rupalkhilari 
Initiated a pull request, Rupal. Please review it and please let me know what you think.

Reg this issue and issue 73:
I added the tests. Incorporated the feedback you gave.
Had to re-work the code as I wanted the username and password change forms to look and function like login/registration forms. I have tested the code, in addition to adding automated tests, and it is working fine.

**Comment by kushankr** [comment]
PR#82

**Comment by rupalkhilari** [comment]
Thanks Kushank !
