### ISSUE TITLE
Allow the user to change his/her password

### ISSUE THREAD

**Issue by rupalkhilari** [electology/approval_frame#73]
The user should be given the ability to change his/her password via an accounts information page (created as a part of https://github.com/electology/approval_frame/issues/72)

**Comment by kushankr** [comment]
Working on it!

**Comment by kushankr** [comment]
Done with this! Incorporated the feedback Rupal gave.

Testing now!

**Comment by kushankr** [comment]
@rupalkhilari 
Initiated a pull request, Rupal. Please review it and please let me know what you think.

**Comment by rupalkhilari** [comment]
Thanks a ton, Kushank ! I shall check it out and let you know within a day or two.

**Comment by kushankr** [comment]
PR#82

**Comment by rupalkhilari** [comment]
Thanks Kushank !
