### ISSUE TITLE
Creator can place an external link next to an option.

### ISSUE THREAD

**Issue by rupalkhilari** [electology/approval_frame#77]
Allow the creator of a poll to place an external link next to an option. Perhaps it could allow the user to use markdown link syntax  to start with, or add a link/button to create the external link.

**Comment by kushankr** [comment]
Aaron mentioned this issue in his email. I am going to start working on this.

**Comment by kushankr** [comment]
Initiated a PR

#98

**Comment by rupalkhilari** [comment]
Thanks, Kushank !
