### ISSUE TITLE
Leading option has different color

### ISSUE THREAD

**Issue by rupalkhilari** [electology/approval_frame#78]
Allow the poll to be configured to display the option with the leading number of votes in a different color. 
This option could be added to the 'Poll Settings' panel while creating a new poll.

**Comment by kushankr** [comment]
I will take this one too. I am working on a couple of issues and I will be able to submit a PR for all of them by the end of next week.

**Comment by kushankr** [comment]
Initiated a PR

#96

**Comment by rupalkhilari** [comment]
I checked your PR and it all works great functionality wise, but I am not sure if the current requirement is to display the different color in the results page or in the voting page. I am checking with Aaron regarding it just to clear my understanding of it and it's difference from #46

**Comment by rupalkhilari** [comment]
Aaron confirmed that this is the expected functionality, so all is good :smile:

**Comment by kushankr** [comment]
Thank you, Rupal for confirming this.

**Comment by rupalkhilari** [comment]
Addressed in https://github.com/electology/approval_frame/pull/96 . Thanks, Kushank !

**Comment by kushankr** [comment]
@rupalkhilari 

Thank you for reviewing and closing PR 103.

Regarding this issue:
Aaron mentioned in his email that leading option should always have a different color. This was implemented here but I made it configurable as per the requirements. Aaron said that 'I would go with making the poll leader bar highlighted as the default.' Hence, I think that I need to make some modifications.

Can you please answer a question I have regarding this change? We can go about this change in 2 ways: 

1) Make the checkbox (corresponding to leading option color) in the poll settings panel checked as default. One drawback would be that this change would only affect the polls created in future but the past polls would still not show the leading option color as green (depending on configuration).

2) Remove the checkbox (corresponding to leading option color) from the poll settings panel and remove the configurable part. For all polls (future and past), this would highlight the poll leader bar as the default.

Which one do you prefer?

Thanks, Rupal. I look forward to your reply.
