### ISSUE TITLE
Create optional countdown for when a poll closes

### ISSUE THREAD

**Issue by rupalkhilari** [electology/approval_frame#81]
Following the implementation of https://github.com/electology/approval_frame/issues/15 , when poll closing date/times are added to a poll, create an optional countdown for whien a poll closes.

**Comment by kushankr** [comment]
Will Work on this!

**Comment by kushankr** [comment]
Will be working on this!

**Comment by kushankr** [comment]
@rupalkhilari 

Hi Rupal,

Should display of poll countdown be configurable in poll settings panel? Can a user select if he/she wants a poll countdown to be displayed (while creating a poll)?
OR
Should ALL polls that have a closing date and time and whose closing date and time is not reached should show a poll countdown? 

Thanks.

**Comment by rupalkhilari** [comment]
Hi Kushank, 
I think the user should have 2 options in the Poll Settings panel: 
1) One for displaying the end datetime of the poll (displays very small static text - perhaps somewhere below the Vote button or any other place which is visible to the user)
2) Another for displaying the countdown which could take from the user 'x' days, 'y' hours before the poll closes. (displays a countdown ticker/time left)

So the user can choose either none, one or both options. I think this would give additional flexibility when it comes to having the poll embedded in a page since If the ticker is continuous right from the beginning it might be distracting - since the poll might only be a small part of the page.

What are your thoughts on this ? Are you planning to include a continuous ticker with seconds, or display either days/hours/minutes depending on the amount of time left ?

**Comment by kushankr** [comment]
Hi Rupal,

I was planning to include a continuous ticker with seconds. I feel that it would be a lot better. 

I was thinking to include only the ticker just below the 'vote' button. But if we are adding two options - displaying end datetime as well as countdown ticker, I can do it the way you have suggested.

Thanks, Rupal!

**Comment by rupalkhilari** [comment]
Cool, sounds good @kushankr. I think the user will have more flexibility with both options and can customize the poll according to his/her preference.

**Comment by kushankr** [comment]
#94 

Initiated a PR. Thanks, Rupal.

**Comment by rupalkhilari** [comment]
Addressed in https://github.com/electology/approval_frame/pull/94
Thanks, Kushank !
